export const ACTION_TYPE = {
	SET_USER: 'SET_USER',
	LOGOUT: 'LOGOUT',
	CLOSE_MODAL: 'CLOSE_MODAL',
	OPEN_MODAL: 'OPEN_MODAL',
	REFRESH_FLAG: 'REFRESH_FLAG',
	SET_PRODUCTS: 'SET_PRODUCTS',
	REMOVE_PRODUCT: 'REMOVE_PRODUCT',
	ADD_PRODUCT: 'ADD_PRODUCT',
	SET_PRODUCT_DATA: 'SET_PRODUCT_DATA',
	SET_IS_LOADING: 'SET_IS_LOADING',
	SET_LAST_PAGE: 'SET_LAST_PAGE',
}
